### PR TITLE
Finishing oldAppleClone

### PR DESCRIPTION
**Pull request by EdCrux**
**Apple Clone page:**

- Created a navigation bar with a gradient background.
- Added aside section with four background images
- Added links to the aside section
- Created the footer section with all the links

Thanks in advance for feedback

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Pull request should be more descriptive, aside section should have four links.

**Comment by pelzolga123** [comment]
## Hi Eduardo!  
### Your project looks :+1: amazing!
### Kudos for great structured README file :1st_place_medal: 

Here are some small changes, that  are required:

* [x] Pull Request should have meaningful title and a short description. You have some text in your pull request description section, but it is not the right one. Name should be changes as well to more descriptive. Correct pull request description should have list of things you implemented in this project. 
For example:

* Created navigation bar with gradient background.
* Added aside section with four background images.

Look at [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from pathwright for detailed description.

* [x] Aside section should contain four links. [Link to website](https://web.archive.org/web/20140301004610/http://www.apple.com/)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Fantastic work @EdCrux! :rocket: 
Your work looks really amazing :smile:. Just two small things to take care of and you can merge. 
#### Design
Your page has a little bit of horizontal scroll going on, please fix this and submit for a re-review.

#### Search box
The hover effect on the search box should be an `onFocus` event instead.

### Summary
You have some really great stuff going on, just look into the two brief issues I have outlined above and you will be great! :+1:

**Review by nikasulo — APPROVED** [review]
# You have done amazingly well @EdCrux  :1st_place_medal: 
Go on and merge :rocket:. See you at the top!

**Pull request merged**
